# Arquivo que define a pipeline de CI-CD

# Define o nome do workflow
name: CI-CD

# Define o evento que deve acountecer para iniciar esta pipeline.
on: 
  # O push define que um commit na branch main irá iniciar esta pipeline.
  push: 
    branches: ["main"]

# Define as tarefas do workflow
jobs:
  build-and-push:
    # Define o sistema operacional onde o job deve ser executado.
    runs-on: ubuntu-latest
    # ???
    permissions: write
    contents: read

    # Define as etapas do job.
    steps:
      # Adiciona o código em um ambiente virtual
      - name: Checkout
        uses: actions/checkout@v6.0.2

      # Para salvar a imagem em um repositório privado no Github Container Registry é necessário se autenticar através de usuário e senha.
      - name: Login no Github Container Registry
        uses: redhat-actions/podman-login@v1.7
        # Utiliza o github secrets para mascarar o usuário e senha
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      # Criação da imagem docker
      - name: Build da imagem
        run: podman build -t ghcr.io${{ github.repository }}:latest
        # --------------- não precisa -----------------------
        #uses: docker/build-push-action@v7.1.0
        #with:
           # Define o diretório que contém o Dockerfile
          #context: ./src
          #file: ./serc/Dockerfile
          #push: true
          # Define o nome da imagem a ser criada
          #tags: |
            #ldesordi/live-kube-news:v1
            #ldesordi/live-kube-news:latest
        # ----------------------------------------------------
      - name: Push da imagem para o registry
        run: podman push ghcr.io/${{ github.repository }}: latest

  deploy:
    # Define que o CD só será executado depoi do CI ter finalizado.
    meeds: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Adiciona o código em um ambiente virtual
      - uses: actions/checkout@v6.0.2
      - name: Definindo o context
        uses: ???
        with: ???

      # Adiciona ao ambiente virtual o acesso ao servidor remoto através de SSH
      - name: Get SSH key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      # Envia o código para o servidor remoto através de SCP que usa SSH
      - name: Deploy using SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      # Acessa o servidor através de SSH, instala as dependências e reinicia o processo
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
