# Arquivo que define a pipeline de CI-CD

# Define o nome do workflow
name: CI-CD

# Define o evento que deve acountecer para iniciar esta pipeline.
on: 
  # O push define que um commit na branch main irá iniciar esta pipeline.
  push: 
    branches: ["main"]

# Define as tarefas do workflow
jobs:
  CI:
    # Define o sistema operacional onde o job deve ser executado.
    runs-on: ubuntu-latest

    # Define as etapas de cada job.
    steps:
      # Adiciona o código em um ambiente virtual
      - uses: actions/checkout@v6.0.2

      # Para salvar a imagem em um repositório privado no Docker Hub é necessário se autenticar através de usuário e senha.
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v4.1.0
        # Utiliza o github secrets para mascarar o usuário e senha
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      
      # Criação da imagem docker
      - name: Criação da imagem docker
        uses: docker/build-push-action@v7.1.0
        with:
           # Define o diretório que contém o Dockerfile
          context: ./src
          file: ./serc/Dockerfile
          push: true
          # Define o nome da imagem a ser criada
          tags: |
            ldesordi/live-kube-news:v1
            ldesordi/live-kube-news:latest

  CD:
    # Define que o CD só será executado depoi do CI ter finalizado.
    meeds: [CI]
    runs-on: ubuntu-latest
    steps:
      # Adiciona o código em um ambiente virtual
      - uses: actions/checkout@v6.0.2
      - name: Definindo o context
        uses: ???
        with: ???

      # Adiciona ao ambiente virtual o acesso ao servidor remoto através de SSH
      - name: Get SSH key and set permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      # Envia o código para o servidor remoto através de SCP que usa SSH
      - name: Deploy using SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
      # Acessa o servidor através de SSH, instala as dependências e reinicia o processo
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
